version: '3.4'

services:
  
  db:
    image: microsoft/mssql-server-windows-express
    ports:
      - "1434:1433"
    environment: 
      - ACCEPT_EULA=Y
      - sa_password=Sa123#
      
  dockersample:
    depends_on:
       - db
    image: asdrasika/rasikadockersample:v3
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080:80"